apiVersion: v1
kind: Pod
metadata:
  name: stress-test
spec:
  restartPolicy: Never
  containers:
  - name: gitbucket
    image: ghcr.io/gitbucket/gitbucket:4.39.0
    # image: localhost/gitbucket
    ports:
    - containerPort: 8080
      hostPort: 9898
  - name: scripts
    image: localhost/scripts
