apiVersion: v1
kind: Pod
metadata:
  name: stress-test
spec:
  restartPolicy: Never
  containers:
  - name: scripts
    image: localhost/scripts
    env:
    - name: N_REPOS
      value: 10
    - name: N_FILES
      value: 100
    - name: N_BRANCHES
      value: 10
    - name: N_COMMITS
      value: 10
    - name: N_MOD_FILES
      value: 25
