FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image:23.1-jdk-21 AS build-executable-gis
USER root
WORKDIR /app/gis
COPY --from=build-jar-gis /app/gis/target/gis-*.jar target/
COPY --from=build-jar-gis /app/gis/target/lib target/lib
RUN native-image -march=compatibility -cp target/gis-*.jar "org.nqm.Gis" --no-fallback \
-H:IncludeResources=".properties" \
-H:IncludeResources="_gis"
RUN mv org.nqm.gis gis
RUN chmod +x gis
RUN ./gis --version

FROM docker.io/alpine:3.20.1
RUN apk add --no-cache git curl bash uuidgen hyperfine jq gcompat
COPY --chmod=0755 common.sh .
COPY --chmod=0755 prepare.sh .
COPY --chmod=0755 benchmark.sh .
COPY --from=build-executable-gis /app/gis/gis /bin
COPY file_plain_text /
CMD ./prepare.sh && ./benchmark.sh
