FROM docker.io/maven:3.9.7-eclipse-temurin-21-alpine AS build-jar-gis
ARG GIS_COMMIT
RUN apk add --no-cache git
RUN git clone https://github.com/nqminhuit/gis.git /app/gis
WORKDIR /app/gis
RUN git log --pretty=oneline -n 20
RUN git checkout "$GIS_COMMIT" || echo "invalid commit, stay on latest"
RUN mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean package
