name: '[LARGE dataset] Stress test gis'

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Gis commit'
        required: true
        default: ''
      gis-version:
        description: 'Gis version'
        required: false
        default: ''

jobs:

  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - run: podman version
    - name: Make up freespace
      run: |
        echo "before clean up:"
        df -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        echo "after clean up:"
        df -h
    - name: Make executable
      run: chmod +x run_on_large_dataset.sh
    - name: Run test
      run: ./run_on_large_dataset.sh ${{inputs.commit}}
      shell: bash
    - name: Storage used
      run: df -h
    - name: Print report
      run: |
        cat result.md
        cat result.md > $GITHUB_STEP_SUMMARY
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib
    - run: git pull
    - name: Append means number for plot
      run: |
        cat _gis_means | sed '1s/^/${{inputs.commit}} /' >> data/big/gis_means
        cat _gis_st_means | sed '1s/^/${{inputs.commit}} /' >> data/big/gis_st_means
        cat _gis_branches_means | sed '1s/^/${{inputs.commit}} /' >> data/big/gis_branches_means
        cat _gis_branches_nn_means | sed '1s/^/${{inputs.commit}} /' >> data/big/gis_branches_nn_means
        cat _gis_fe_means | sed '1s/^/${{inputs.commit}} /' >> data/big/gis_fe_means
        cat _gis_co_means | sed '1s/^/${{inputs.commit}} /' >> data/big/gis_co_means
        cat _gis_files_means | sed '1s/^/${{inputs.commit}} /' >> data/big/gis_files_means
    - name: Plot performance chart
      run: python plot.py
    - name: Commit & Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "auto: record performance values large dataset"
        file_pattern: 'data/*'
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: "result-${{ inputs.gis-version }}.md"
        path: result.md
