name: '[LARGE dataset] Stress test gis'

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Gis commit'
        required: false
        default: 'latest'
      gis-version:
        description: 'Gis version'
        required: false
        default: ''
      should-commit-stats:
        type: boolean
        description: 'Should commit stats to repo'
        default: false

jobs:
  build:
    runs-on: ubuntu-24.04
    services:
      gitbucket:
        image: ghcr.io/gitbucket/gitbucket:4.39.0
        ports:
          - 9898:8080
    steps:
    - uses: actions/checkout@v4
    - name: Make up freespace
      run: |
        echo "before clean up:"
        df -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        echo "after clean up:"
        df -h
    - name: Run test
      run: ./scripts/stress_test.sh ${{inputs.commit}} large_dataset.yaml
      shell: bash
    - name: Print report
      run: |
        cat result.md
        cat result.md > $GITHUB_STEP_SUMMARY
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib
    - name: Update local repo
      run: |
        git fetch
        git reset --hard origin/$(git branch --show-current)
    - name: Save results for plot
      run: |
        cat _gis_means >> data/big/gis_means
        cat _gis_st_means >> data/big/gis_st_means
        cat _gis_branches_means >> data/big/gis_branches_means
        cat _gis_fe_means >> data/big/gis_fe_means
        cat _gis_co_means >> data/big/gis_co_means
        cat _gis_files_means >> data/big/gis_files_means
        cat _gis_versions >> data/big/gis_versions
        python plot_big.py
    - name: Commit & Push changes
      if: ${{inputs.should-commit-stats}}
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "auto: record performance values large dataset"
        file_pattern: 'data/*'
