name: 'Zero Dawn'

on:
  workflow_dispatch:
    inputs:
      n_commits:
        description: 'Number of latest commits to test'
        required: false
        default: 10
      cmd_list_commits:
        description: 'Command that lists commits to test'
        required: false
        default: ''
        # e.g.,
        # git log --reverse --pretty=format:'%h' fc3996b4f8aceae6954d5aa8a99f8cf5f607d92d.. --no-merges
        # git log --invert-grep --grep="CI" --grep="docs" --grep="dev" --grep="README" --grep="github" --reverse --pretty=format:'%h' fc3996b4f8aceae6954d5aa8a99f8cf5f607d92d.. --no-merges | grep -v a20dcdc

jobs:
  reset-performance-stats:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Clean up
      run: |
        echo "" > data/gis_performance.svg

        for f in $(ls -1 data/gis*_means)
        do {
          echo "" > $f
        }
        done

        for f in $(ls -1 data/big/gis*_means)
        do {
          echo "" > $f
        }
        done
      shell: bash

    - name: Commit & Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "auto: Zero Dawn initiated"
        file_pattern: 'data/*'

    - name: Initiate Zero Dawn with command listing commits
      if: inputs.cmd_list_commits
      run: |
        git clone https://github.com/nqminhuit/gis.git
        cd gis
        SHAS=($(eval ${{inputs.cmd_list_commits}}))
        for c in "${SHAS[@]}"
        do {
              curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.GIS_TOKEN}}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/nqminhuit/gis-stress-test/actions/workflows/stress-test-small.yml/dispatches -d '{"ref":"master", "inputs":{"commit":"'"$c"'"}}'
              sleep 240
            }
        done
      shell: bash

    - name: Initiate Zero Dawn with N latest commits
      if: ${{ !inputs.cmd_list_commits }}
      run: |
        git clone https://github.com/nqminhuit/gis.git
        cd gis
        SHAS=($(git log --reverse --pretty=format:'%h' -n ${{inputs.n_commits}}))
        for c in "${SHAS[@]}"
        do {
              curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.GIS_TOKEN}}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/nqminhuit/gis-stress-test/actions/workflows/stress-test-small.yml/dispatches -d '{"ref":"master", "inputs":{"commit":"'"$c"'"}}'
              sleep 240
            }
        done
      shell: bash
