name: 'Zero Dawn'

on:
  workflow_dispatch:
    inputs:
      n_commits:
        description: 'Number of latest commits to test'
        required: false
        default: 10

jobs:
  reset-performance-stats:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Clean up
      run: |
        echo "" > data/gis_performance.svg

        for f in $(ls -1 data/gis*_means)
        do {
          echo "" > $f
        }
        done

        for f in $(ls -1 data/big/gis*_means)
        do {
          echo "" > $f
        }
        done
      shell: bash

    - name: Commit & Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "auto: delete performance values"
        file_pattern: 'data/*'

    - name: Initiate Zero Dawn
      run: |
        git clone --depth=${{inputs.n_commits}} https://github.com/nqminhuit/gis.git
        cd gis
        SHAS=($(git log --reverse --pretty=format:'%h' -n ${{inputs.n_commits}}))
        for c in "${SHAS[@]}"
        do {
              curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.GIS_TOKEN}}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/nqminhuit/gis-stress-test/actions/workflows/stress-test-small.yml/dispatches -d '{"ref":"master", "inputs":{"commit":"'"$c"'"}}'
              sleep 300
            }
        done
      shell: bash
